######################################################################
##
## Filename: tb_uart.udo
## Created on: Wed Jul 05 0:04:45 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
