######################################################################
##
## Filename: uart_fifo_rx.udo
## Created on: Wed Jul 05 22:54:38 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
