######################################################################
##
## Filename: tb.udo
## Created on: Sun Jul 09 20:41:16 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
